package net.andreu.cafeteria;

import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ListView;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Label;
import javafx.scene.control.ComboBox;
import javafx.scene.input.MouseEvent;


public class SampleController implements Initializable {
	@FXML
	private ComboBox<String> cbxCafes;
	@FXML
	private ComboBox<String> cbxIngredients;
	@FXML
	private Button btnMes;
	@FXML
	private ListView<String> lvTotalIngrdients;
	@FXML
	private Label lblPreuCafe;
	@FXML
	private Button btnAfegirCafe;
	@FXML
	private ListView<String> lvCafes;
	@FXML
	private Label lblTotalComanda;
	@FXML
	private Button btnAcabar;
	
	EntityManager em;
	List<Cafes> LlistaCafes = new ArrayList<>();
	List<Ingredients> LlistaIngredients = new ArrayList<>();
	int preuIngredients = 1;
	int preuComanda = 0;
	ObservableList<String> itemsIngredients = FXCollections.observableArrayList();
	ObservableList<String> itemsCamanda = FXCollections.observableArrayList();
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		EntityManagerFactory emf = Persistence.createEntityManagerFactory("cafetaria");		
		em = emf.createEntityManager();
		
		TypedQuery<Cafes> totsElsCafes= em.createQuery("SELECT c FROM Cafes c", Cafes.class);
		LlistaCafes = totsElsCafes.getResultList();
		
		cbxCafes.setValue("Tria un cafè");
		for(Cafes c : LlistaCafes){
			cbxCafes.getItems().add(c.toString());
			
		}
		
		
		TypedQuery<Ingredients> totsElsIngredients= em.createQuery("SELECT i FROM Ingredients i", Ingredients.class);
		LlistaIngredients = totsElsIngredients.getResultList();
		
		cbxIngredients.setValue("Tria ingredients");
		for(Ingredients i : LlistaIngredients){
			cbxIngredients.getItems().add(i.toString());
		}
	}
	
	// Event Listener on Button[#btnMes].onMouseClicked
	@FXML
	public void AfegirIngredient(MouseEvent event) {
		int posicioIngredient = 0;
		int preuObtingut = 0;
		
		String igredient = cbxIngredients.getValue();
		
		itemsIngredients.add(igredient);
		lvTotalIngrdients.setItems(itemsIngredients);
		
		while (!igredient.equals(LlistaIngredients.get(posicioIngredient).getNom()) && posicioIngredient < LlistaIngredients.size()) {
			posicioIngredient++;
		}
		preuObtingut = LlistaIngredients.get(posicioIngredient).getPreu();
		preuIngredients += preuObtingut;
		
		lblPreuCafe.setText(""+preuIngredients);
	}
	
	// Event Listener on Button[#btnAfegirCafe].onMouseClicked
	@FXML
	public void AfegirCafe(MouseEvent event) {
		String cafeTriat = cbxCafes.getValue();
		
		if(cafeTriat.equals("Tria un cafè")){
			Alert alert = new Alert(AlertType.INFORMATION);
			alert.setTitle("Information Dialog");
			alert.setHeaderText(null);
			alert.setContentText("No has triat cap cafè");
			alert.showAndWait();
		}else{
			
			for(int i=0; i<itemsIngredients.size(); i++){
				cafeTriat+= ", "+itemsIngredients.get(i);
			}
			
			itemsCamanda.add(cafeTriat);
			lvCafes.setItems(itemsCamanda);;
			
			preuComanda += preuIngredients;
			lblTotalComanda.setText(""+preuComanda);
		}
	}
	
	// Event Listener on Button[#btnAcabar].onMouseClicked
	@FXML
	public void AcabaComanda(MouseEvent event) {
		// TODO Autogenerated
	}
}
